name: Secret scan
on: pull_request
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Scan secrets
        run: docker run -v "$(pwd):$(pwd)" -w "$(pwd)" --rm secretlint/secretlint --maskSecrets '**/*'
