name: Secret scan
on: pull_request
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  secretlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Scan secrets
        run: docker run -v "$(pwd):$(pwd)" -w "$(pwd)" --rm secretlint/secretlint secretlint --maskSecrets '**/*'
