name: Secret scan
on: pull_request
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  secretlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Scan secrets
        run: docker run -v "$(pwd):$(pwd)" -w "$(pwd)" --rm secretlint/secretlint secretlint --maskSecrets '**/*'
